swagger: "2.0"
info:
    description: API to manage local copies of youtube music playlists
    version: "1.0.0"
    title: Youtube Playman API
consumes:
    - "application/json"
produces:
    - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
    /people:
        get:
            operationId: "people.read"
            tags:
                - "People"
            summary: "The people data structure supported by the server application"
            description: "Read the list of people"
            responses:
                200:
                    description: "Successful read people list operation"
                    schema:
                        type: "array"
                        items:
                            properties:
                                fname:
                                    type: "string"
                                lname:
                                    type: "string"
                                timestamp:
                                    type: "string"
